// <auto-generated />
using HotWheels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HotWheels.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotWheels.Models.CTDonHang", b =>
                {
                    b.Property<int>("ID_CTDonHang")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Gia");

                    b.Property<int>("ID_DonHang");

                    b.Property<int>("ID_SanPham");

                    b.Property<int>("SoLuong");

                    b.HasKey("ID_CTDonHang");

                    b.HasIndex("ID_DonHang");

                    b.HasIndex("ID_SanPham");

                    b.ToTable("CTDonHangDb");
                });

            modelBuilder.Entity("HotWheels.Models.CTGioHang", b =>
                {
                    b.Property<int>("ID_CTGioHang")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ID_GioHang");

                    b.Property<int?>("SanPhamID_SanPham");

                    b.Property<int>("SoLuong");

                    b.HasKey("ID_CTGioHang");

                    b.HasIndex("ID_GioHang");

                    b.HasIndex("SanPhamID_SanPham");

                    b.ToTable("CTGioHangDb");
                });

            modelBuilder.Entity("HotWheels.Models.DonHang", b =>
                {
                    b.Property<int>("ID_DonHang")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<string>("HoVaTen");

                    b.Property<DateTime>("NgayDat");

                    b.Property<string>("SoDienThoai");

                    b.Property<decimal>("TongTien");

                    b.HasKey("ID_DonHang");

                    b.ToTable("DonHangDb");
                });

            modelBuilder.Entity("HotWheels.Models.GioHang", b =>
                {
                    b.Property<string>("ID_GioHang")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID_GioHang");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("HotWheels.Models.SanPham", b =>
                {
                    b.Property<int>("ID_SanPham")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Anh");

                    b.Property<string>("ChatLieu");

                    b.Property<decimal>("DonGia");

                    b.Property<int>("ID_ThuongHieu");

                    b.Property<string>("MoTa");

                    b.Property<string>("TenSanPham");

                    b.Property<string>("TyLe");

                    b.Property<string>("XuatXu");

                    b.HasKey("ID_SanPham");

                    b.HasIndex("ID_ThuongHieu");

                    b.ToTable("SanPhamDb");
                });

            modelBuilder.Entity("HotWheels.Models.TaiKhoan", b =>
                {
                    b.Property<int>("ID_TaiKhoan")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("ID_TaiKhoan");

                    b.ToTable("TaiKhoanDb");
                });

            modelBuilder.Entity("HotWheels.Models.ThuongHieu", b =>
                {
                    b.Property<int>("ID_ThuongHieu")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenThuongHieu");

                    b.HasKey("ID_ThuongHieu");

                    b.ToTable("ThuongHieuDb");
                });

            modelBuilder.Entity("HotWheels.Models.CTDonHang", b =>
                {
                    b.HasOne("HotWheels.Models.DonHang", "DonHang")
                        .WithMany("CTDonHang")
                        .HasForeignKey("ID_DonHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HotWheels.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("ID_SanPham")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HotWheels.Models.CTGioHang", b =>
                {
                    b.HasOne("HotWheels.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHang")
                        .HasForeignKey("ID_GioHang");

                    b.HasOne("HotWheels.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamID_SanPham");
                });

            modelBuilder.Entity("HotWheels.Models.SanPham", b =>
                {
                    b.HasOne("HotWheels.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("ID_ThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
